services:
  - type: web
    name: nifty-bot
    healthCheckPath: /
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/bot_listener.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
